version: "3.5"
services:
    oracle:
        image: oracle/database:11.2.0.2-xe
        ports:
            - "11521:1521"
        environment:
            - ORACLE_PWD=testing12345
        build:
          context: .
          shm_size: '2gb'
        shm_size: '2gb'
